/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author henrique
 */
public class CoffeMachineSimulatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form CoffeMachineSimulatorWindow
     */
    public CoffeMachineSimulatorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        clockLabel = new javax.swing.JLabel();
        clockHourLabel = new javax.swing.JLabel();
        clockMinuteLabel = new javax.swing.JLabel();
        clockMinuteSpinner = new javax.swing.JSpinner();
        clockHourSpinner = new javax.swing.JSpinner();
        inUseLabel = new javax.swing.JLabel();
        inUseValueLabel = new javax.swing.JLabel();
        waterLevelLabel = new javax.swing.JLabel();
        waterLevelValueLabel = new javax.swing.JLabel();
        waterLevelUnitLabel = new javax.swing.JLabel();
        coffeLevelLabel = new javax.swing.JLabel();
        coffeLevelValueLabel = new javax.swing.JLabel();
        coffeLevelUnitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Simulador da Cafeteira");

        clockLabel.setText("Relógio interno:");

        clockHourLabel.setText("hs");

        clockMinuteLabel.setText("min");

        clockHourSpinner.setName(""); // NOI18N

        inUseLabel.setText("Fazendo café?");

        inUseValueLabel.setText("Sim.");

        waterLevelLabel.setText("Quantidade de água:");

        waterLevelValueLabel.setText("1");

        waterLevelUnitLabel.setText("xícara");

        coffeLevelLabel.setText("Quantidade de café:");

        coffeLevelValueLabel.setText("2");

        coffeLevelUnitLabel.setText("colher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clockLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clockHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clockHourLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clockMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clockMinuteLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inUseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inUseValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(waterLevelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waterLevelValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waterLevelUnitLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(coffeLevelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coffeLevelValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coffeLevelUnitLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(titleLabel)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockLabel)
                    .addComponent(clockHourLabel)
                    .addComponent(clockMinuteLabel)
                    .addComponent(clockMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inUseLabel)
                    .addComponent(inUseValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterLevelLabel)
                    .addComponent(waterLevelValueLabel)
                    .addComponent(waterLevelUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffeLevelLabel)
                    .addComponent(coffeLevelValueLabel)
                    .addComponent(coffeLevelUnitLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void showWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeMachineSimulatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeMachineSimulatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeMachineSimulatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeMachineSimulatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeMachineSimulatorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel clockHourLabel;
    private javax.swing.JSpinner clockHourSpinner;
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel clockMinuteLabel;
    private javax.swing.JSpinner clockMinuteSpinner;
    private javax.swing.JLabel coffeLevelLabel;
    private javax.swing.JLabel coffeLevelUnitLabel;
    private javax.swing.JLabel coffeLevelValueLabel;
    private javax.swing.JLabel inUseLabel;
    private javax.swing.JLabel inUseValueLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel waterLevelLabel;
    private javax.swing.JLabel waterLevelUnitLabel;
    private javax.swing.JLabel waterLevelValueLabel;
    // End of variables declaration//GEN-END:variables
}
